import { precacheAndRoute } from 'workbox-precaching';

// Precaches all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const VERSION = "adblock-v4-streaming";

// Known ad/tracker domains to block
// Includes networks commonly used by streaming embed sites (vidking, etc.)
const BLOCKED_DOMAINS = [
  // Generic ad networks
  "turnixamtman.com",
  "doubleclick.net",
  "googlesyndication.com",
  "adservice.google.com",
  "pagead2.googlesyndication.com",
  "adnxs.com",
  "exoclick.com",
  "popcash.net",
  "popads.net",
  "trafficjunky.net",
  "adsrvr.org",
  "taboola.com",
  "outbrain.com",
  "revcontent.com",
  "media.net",
  "adcolony.com",
  "moatads.com",
  "criteo.com",
  "rubiconproject.com",
  "openx.net",
  "pubmatic.com",
  "advertising.com",
  "adf.ly",
  "linkvertise.com",
  "shorte.st",
  "ouo.io",
  "bc.vc",
  "za.gl",
  "n9.cl",
  "sh.st",
  "clk.sh",
  "oxy.st",
  "exe.io",
  "adfly",
  "clickadu.com",
  "propellerads.com",
  "hilltopads.net",
  "adsterra.com",
  "bidvertiser.com",
  "mgid.com",
  "zeropark.com",
  "trafficfactory.biz",
  "plugrush.com",
  // Streaming embed site ad networks (vidking + similar)
  "vstsrv.com",
  "srvtrck.com",
  "mgjuqx.com",
  "syndication.revcontent.com",
  "go.bnc.lt",
  "adspyglass.com",
  "spyglass.com",
  "smartadserver.com",
  "ad.plus",
  "adplus.io",
  "primis.tech",
  "cdn.primis.tech",
  "springserve.com",
  "vidazoo.com",
  "cdn.vidazoo.com",
  "undertone.com",
  "cdn.undertone.com",
  "yieldmo.com",
  "amazon-adsystem.com",
  "aps.amazon.com",
  "analyticsengine.co",
  "adform.net",
  "ad.gt",
  "cdn.adhese.com",
  "srv.ad",
  "jwpads.com",
  "player.ads.video",
  "imasdk.googleapis.com",
  "pagead2.googlesyndication.com",
  "securepubads.g.doubleclick.net",
  "tpc.googlesyndication.com",
  "fundingchoicesmessages.google.com",
  "video.unrulymedia.com",
  "unrulymedia.com",
  "quantserve.com",
  "scorecardresearch.com",
  "demdex.net",
  "everesttech.net",
  "2mdn.net",
  "flashtalking.com",
  "adloox.com",
  "apsalar.com",
  "segment.io",
  "mixpanel.com",
  "hotjar.com",
  "mouseflow.com",
  "luckyorange.com",
  "fullstory.com",
  "loggly.com",
  "bugsnag.com",
];

// Domains that should ALWAYS be allowed through
const ALWAYS_ALLOWED = [
  "localhost",
  "api.themoviedb.org",
  "image.tmdb.org",
  "themoviedb.org",
  "supabase.co",
  "vidking.net",
  "www.vidking.net",
  "youtube.com",
  "youtube-nocookie.com",
  "youtu.be",
  "googleapis.com",
  "googlevideo.com",
  "corsproxy.io",
  "allorigins.win",
  "zuup.dev",
];

const isAlwaysAllowed = (hostname) => {
  return ALWAYS_ALLOWED.some(
    (d) => hostname === d || hostname.endsWith("." + d)
  );
};

const isBlocked = (url) => {
  try {
    const parsed = new URL(url);
    const hostname = parsed.hostname.toLowerCase();

    // Never block always-allowed domains
    if (isAlwaysAllowed(hostname)) return false;

    // Check domain blocklist
    for (const domain of BLOCKED_DOMAINS) {
      if (hostname === domain || hostname.endsWith("." + domain)) {
        return true;
      }
    }

    return false;
  } catch {
    return false;
  }
};

// Install: skip waiting to activate immediately
self.addEventListener("install", (event) => {
  console.log("[SW AdBlock] Installing v" + VERSION);
  self.skipWaiting();
});

// Activate: take control of all clients immediately
self.addEventListener("activate", (event) => {
  console.log("[SW AdBlock] Active ✓");
  event.waitUntil(self.clients.claim());
});

// Ad blocker disabled: no fetch interception
// This service worker is now a no-op for all fetch events.
